# Generated by Django 3.1.13 on 2021-08-02 07:57

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('due_past_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
