# Generated by Django 3.1.13 on 2021-08-02 08:32

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210802_1227'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('empty_category', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='task',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(default='general', related_name='tasks', to='todo.Category'),
        ),
    ]
